WebApplication/Models/SignUpFirstViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    public class SignUpFirstViewModel
    {
        [Required (ErrorMessage = "Не указано имя")]
        public string FirstName { get; set; }

        [Required (ErrorMessage = "Не указана фамилия")]
        public string LastName { get; set; }

        [Required (ErrorMessage = "Не указан день рожденья")]
        public DateTime Birthday { get; set; }

        [Required (ErrorMessage = "Не указан пол")]
        public Gender Gender { get; set; }
    }
}

WebApplication/Models/SignUpSecondViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    public class SignUpSecondViewModel
    {
        [Required(ErrorMessage = "Не указано имя")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Не указана фамилия")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Не указана дата рождения")]
        public DateTime Birthday { get; set; }

        [Required(ErrorMessage = "Не указан пол")]
        public Gender Gender { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Не указан email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Пароли не совпадают")]
        public string ConfirmPassword { get; set; }
        public bool IsRemember { get; set; }
    }
}

WebApplication/Controllers/MockupsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class MockupsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            var model = new SignUpFirstViewModel
            {
                Birthday = DateTime.Now
            };

            return View("SignUpFirst", model);
        }

        [HttpPost]
        public IActionResult SignUp(SignUpFirstViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("SignUpFirst", model);
            }

            var signUpSecondViewModel = new SignUpSecondViewModel
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Birthday = model.Birthday,
                Gender = model.Gender
            };

            return View("SignUpSecond", signUpSecondViewModel);
        }

        [HttpPost]
        public IActionResult SignUpComplete(SignUpSecondViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("SignUpSecond", model);
            }

            var user = new User
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Birthday = model.Birthday,
                Gender = model.Gender,
                Email = model.Email,
                Password = model.Password
            };

            return View("SignUpResult", user);
        }

        [HttpGet]
        public IActionResult PasswordReset()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PasswordReset(PasswordResetModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return View("VerifyPasswordReset");
        }

        [HttpGet]
        public IActionResult VerifyPasswordReset()
        {
            return View();
        }

        [HttpPost]
        public IActionResult VerifyPasswordReset(VerifyPasswordResetModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.Code != "AdminCode" && model.Code != "123")
            {
                ModelState.AddModelError("Code", "Неверный код");

                return View(model);
            }

            return View("VerifyPasswordResetResult");
        }
    }
}

WebApplication/Views/Mockups/Index.cshtml
@{
    ViewData["Title"] = "Multi-staged forms";
}

<h1>@ViewData["Title"]</h1>

<div class="list-group">
    <a asp-controller="Mockups" asp-action="PasswordReset" class="list-group-item list-group-item-action">
        Password reset
    </a>
    <a asp-controller="Mockups" asp-action="SignUp" class="list-group-item list-group-item-action">
        Sign up
    </a>
</div>

WebApplication/Views/Mockups/PasswordReset.cshtml
@model WebApplication.Models.PasswordResetModel
@{
    ViewData["Title"] = "Reset your password";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Mockups" asp-action="PasswordReset" method="post">

    <div class="form-group">
        <label>Email</label>
        <input asp-for="@Model.Email" type="email" class="form-control">
        <span asp-validation-for="@Model.Email" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Отправить код</button>
    <a asp-action="VerifyPasswordReset" class="btn btn-secondary">У меня уже есть код</a>
</form>

WebApplication/Views/Mockups/SignUpFirst.cshtml
@model WebApplication.Models.SignUpFirstViewModel
@{
    ViewData["Title"] = "SignUp";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Mockups" asp-action="SignUp" method="post">
    <div class="form-group">
        <label>Имя</label>
        <input asp-for="@Model.FirstName" type="text" class="form-control">
        <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Фамилия</label>
        <input asp-for="@Model.LastName" type="text" class="form-control">
        <span asp-validation-for="@Model.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>День рожденья</label>
        <input asp-for="@Model.Birthday" type="date" class="form-control">
        <span asp-validation-for="@Model.Birthday" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Пол</label>
        <div class="form-check">
            <input asp-for="@Model.Gender" class="form-check-input" type="radio" value="Male" checked>
            <label class="form-check-label">
                Мужчина
            </label>
        </div>
        <div class="form-check">
            <input asp-for="@Model.Gender" class="form-check-input" type="radio" value="Female">
            <label class="form-check-label">
                Женщина
            </label>
        </div>
        <span asp-validation-for="@Model.Gender" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>

WebApplication/Views/Mockups/SignUpResult.cshtml
@model WebApplication.Models.User
@{
    ViewData["Title"] = "Sign up result";
}

<h1>@ViewData["Title"]</h1>

<dl class="row">
    <dt class="col-3">
        Имя
    </dt>
    <dd class="col-9">
        <span class="badge badge-light">@Model.FirstName</span>
    </dd>
    <dt class="col-3">
        Фамилия
    </dt>
    <dd class="col-9">
        <span class="badge badge-light">@Model.LastName</span>
    </dd>
    <dt class="col-3">
        День рожденья
    </dt>
    <dd class="col-9">
        <span class="badge badge-light">@Model.Birthday.ToShortDateString()</span>
    </dd>
    <dt class="col-3">
        Пол
    </dt>
    <dd class="col-9">
        @if (Model.Gender == Gender.Male)
        {
            <span class="badge badge-light">Мужской</span>
        }
        else
        {
            <span class="badge badge-light">Женский</span>
        }

    </dd>
    <dt class="col-3">
        Email
    </dt>
    <dd class="col-9">
        <span class="badge badge-light">@Model.Email</span>
    </dd>
    <dt class="col-3">
        Пароль
    </dt>
    <dd class="col-9">
        <span class="badge badge-light">@Model.Password</span>
    </dd>
</dl>

WebApplication/Views/Mockups/SignUpSecond.cshtml
@model WebApplication.Models.SignUpSecondViewModel
@{
    ViewData["Title"] = "SignUp";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Mockups" asp-action="SignUpComplete" method="post">
    @Html.HiddenFor(model => model.FirstName)
    @Html.HiddenFor(model => model.LastName)
    @Html.HiddenFor(model => model.Birthday)
    @Html.HiddenFor(model => model.Gender)

    <div class="form-group">
        <label>Email</label>
        <input asp-for="@Model.Email" type="email" class="form-control">
        <span asp-validation-for="@Model.Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Пароль</label>
        <input asp-for="@Model.Password" type="password" class="form-control">
        <span asp-validation-for="@Model.Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Подтвердите пароль</label>
        <input asp-for="@Model.ConfirmPassword" type="password" class="form-control">
        <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>
    </div>
    <div class="form-check">
        <input asp-for="@Model.IsRemember" type="checkbox" class="form-check-input">
        <label class="form-check-label" for="exampleCheck1">Запомнить меня</label>
    </div>

    <button type="submit" class="btn btn-primary">Завершить регистрацию</button>
</form>

WebApplication/Views/Mockups/VerifyPasswordReset.cshtml
@model WebApplication.Models.VerifyPasswordResetModel
@{
    ViewData["Title"] = "Reset your password";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Mockups" asp-action="VerifyPasswordReset" method="post">
    <div class="form-group">
        <label>Код</label>
        <input asp-for="@Model.Code" type="text" class="form-control">
        <span asp-validation-for="@Model.Code" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Подтвердить</button>
</form>

WebApplication/Views/Mockups/VerifyPasswordResetResult.cshtml
@{
    ViewData["Title"] = "Reset result";
}

<h1>@ViewData["Title"]</h1>

<h2>Ok</h2>