WebApplication/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class CalcController : Controller
    {
        private const int secretToken = 55;

        public IActionResult ManualSingle()
        {
            if (Request.Method.ToLower() == "post")
            {
                return FormHandler();
            }

            return View();
        }

        [HttpGet]
        public IActionResult ManualSeparate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ManualSeparate(int token)
        {
            if (token != secretToken)
            {
                return Forbid();
            }

            return FormHandler();
        }

        private IActionResult FormHandler()
        {
            var firstString = Request.Form.FirstOrDefault(p => p.Key == "first").Value;
            var first = Int32.Parse(firstString);

            var secondString = Request.Form.FirstOrDefault(p => p.Key == "second").Value;
            var second = Int32.Parse(secondString);

            var operationString = Request.Form.FirstOrDefault(p => p.Key == "operation").Value;
            var operationInt = Int32.Parse(operationString);
            var operation = (Operation)operationInt;

            return View("Result", new ResultModel(first, second, operation));
        }

        public IActionResult ModelParameters(CalcModel model)
        {
            if (Request.Method.ToLower() == "post")
            {
                return View("Result", new ResultModel(model));
            }

            return View();
        }

        [HttpGet]
        public IActionResult ModelSeparate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ModelSeparate(CalcModel model)
        {
            return View("Result", new ResultModel(model));
        }
    }
}

WebApplication/Views/Calc/ManualSeparate.cshtml
@{
    ViewData["Title"] = "Manual Separate";
}

<form asp-controller="Calc" asp-action="ManualSeparate" method="post" asp-route-token="55">
    <div class="form-row">
        <div class="form-group col-md-5">
            <input type="number" class="form-control" name="first">
        </div>
        <div class="form-group col-md-2">
            <select name="operation" class="form-control">
                <option selected value="0">+</option>
                <option value="1">-</option>
                <option value="2">*</option>
                <option value="3">/</option>
            </select>
        </div>
        <div class="form-group col-md-5">
            <input type="number" class="form-control" name="second">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Посчитать</button>
</form>

WebApplication/Views/Calc/ManualSingle.cshtml
@{
    ViewData["Title"] = "Manual Single";
}

<form asp-controller="Calc" asp-action="ManualSingle" method="post">
    <div class="form-row">
        <div class="form-group col-md-5">
            <input type="number" class="form-control" name="first">
        </div>
        <div class="form-group col-md-2">
            <select name="operation" class="form-control">
                <option selected value="0">+</option>
                <option value="1">-</option>
                <option value="2">*</option>
                <option value="3">/</option>
            </select>
        </div>
        <div class="form-group col-md-5">
            <input type="number" class="form-control" name="second">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Посчитать</button>
</form>

WebApplication/Views/Calc/ModelParameters.cshtml
@model WebApplication.Models.CalcModel
@{
    ViewData["Title"] = "Model Parameters";
}

<form asp-controller="Calc" asp-action="ModelParameters" method="post">
    <div class="form-row">
        <div class="form-group col-md-5">
            <input asp-for="@Model.First" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <select asp-for="@Model.Operation" class="form-control">
                <option selected value="0">+</option>
                <option value="1">-</option>
                <option value="2">*</option>
                <option value="3">/</option>
            </select>
        </div>
        <div class="form-group col-md-5">
            <input asp-for="@Model.Second" class="form-control">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Посчитать</button>
</form>

WebApplication/Views/Calc/ModelSeparate.cshtml
@model WebApplication.Models.CalcModel
@{
    ViewData["Title"] = "Model Separate";
}

<form asp-controller="Calc" asp-action="ModelSeparate" method="post">
    <div class="form-row">
        <div class="form-group col-md-5">
            <input asp-for="@Model.First" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <select asp-for="@Model.Operation" class="form-control">
                <option selected value="0">+</option>
                <option value="1">-</option>
                <option value="2">*</option>
                <option value="3">/</option>
            </select>
        </div>
        <div class="form-group col-md-5">
            <input asp-for="@Model.Second" class="form-control">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Посчитать</button>
</form>

WebApplication/Views/Calc/Result.cshtml
@model WebApplication.Models.ResultModel
@{
    ViewData["Title"] = "Result";
}

<h1>@ViewData["Title"]</h1>

<h2>@Model.Result</h2>